### ISSUE TITLE
Bug: Archive missions are loaded multiple times when connection to API is lost and bot is reconnecting

### ISSUE THREAD

**Issue by Ilddor** [ArmaForces/Boderator#4]

**Comment by Smieszkokoleszko** [comment]
Couldn't recreate this. Archived missions are loaded once on startup and once while reconnecting or not multiply while reloading.

**Comment by 3Mydlo3** [comment]
I think this is related to fetching the archived missions on each reconnect. If you enter debugging and place a breakpoint there it will be consistently hit every few minutes. Maybe we should block this to once every hour or so as the archived missions don't change frequently.

**Comment by 3Mydlo3** [comment]
Probably fixed by #47
