### ISSUE TITLE
API returns negative "freeSlots" value for one of the missions

### ISSUE THREAD

**Issue by jskowronski39** [ArmaForces/Boderator#5]
This results in incorrect value displayed for number of occupied slots.

Raw response that we are getting from the API:
![image](https://user-images.githubusercontent.com/20958025/74084939-5fac2380-4a74-11ea-89a5-52168f8e23ff.png)

Website preview:
![image](https://user-images.githubusercontent.com/20958025/74084953-7d798880-4a74-11ea-98cc-053efad36c36.png)

**Comment by 3Mydlo3** [comment]
I guess this was fixed but not closed as ther are no negative `freeSlots` in API anymore.
